export const SET_BOOKS = 'SET_BOOKS';
export const SET_CURRENT_BOOKS = 'SET_CURRENT_BOOKS';
export const SET_WANT_BOOKS = 'SET_WANT_BOOKS';
export const SET_READ_BOOKS = 'SET_READ_BOOKS';

export const SET_FILTERED_BOOKS = 'SET_FILTERED_BOOKS';

export const FETCH_BOOKS_START = 'FETCH_BOOKS_START';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAIL = ' FETCH_BOOKS_FAIL';
