export const SET_BOOKS = 'SET_BOOKS';
export const SET_BOOK_ON_SHELF = 'SET_BOOK_ON_SHELF';

export const FETCH_BOOKS_START = 'FETCH_BOOKS_START';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAIL = ' FETCH_BOOKS_FAIL';

export const UPDATE_SHELVES = 'UPDATE_SHELVES';
export const REMOVE_BOOK_FROM_ALL = 'REMOVE_BOOK_FROM_ALL';
